### PR TITLE
Center mouse cursor before quitting SDL's video subsystem

### LINKED ISSUE #299: [BUG]  macOS segfaulting upon exit
### Russian Doom version

Russian Doom 5.1

### What Operating System are you using?

Other

### What Build variant of Russian Doom are you using?

x64 (amd64, x86_64, win64)

### If Other OS or Build variant, please describe

macOS arm64 (Apple Silicon) and x86_64

### Relevant hardware info

Intel Core i5 4250U, HD Graphics 5000 (1024MB) | Apple Silicon M1 with 8-Core GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When exiting Russian Doom (from anywhere it does not matter) a segfault appears (see below on Debug with full Backtrace on Clang):

```
2021-12-27 07:05:27.445271+0100 russian-doom[45383:385803] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=45383
2021-12-27 07:05:27.445582+0100 russian-doom[45383:385803] SecTaskCopyDebugDescription: russian-doom[45383]/0#-1 LF=0
2021-12-27 07:05:29.015211+0100 russian-doom[45383:385803] MTLIOAccelDevice bad MetalPluginClassName property (null)
2021-12-27 07:05:29.018401+0100 russian-doom[45383:385803] +[MTLIOAccelDevice registerDevices]: Zero Metal services found
2021-12-27 07:05:29.158748+0100 russian-doom[45383:385803] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=45383
2021-12-27 07:05:29.158861+0100 russian-doom[45383:385803] SecTaskCopyDebugDescription: russian-doom[45383]/0#-1 LF=0
Process 45383 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x000000010078627e libSDL2-2.0.0.dylib`Cocoa_WarpMouseGlobal + 142
libSDL2-2.0.0.dylib`Cocoa_WarpMouseGlobal:
->  0x10078627e <+142>: movsd  %xmm0, 0x8(%rax)
    0x100786283 <+147>: movsd  -0x28(%rbp), %xmm1        ; xmm1 = mem[0],zero 
    0x100786288 <+152>: movsd  %xmm1, 0x10(%rax)
    0x10078628d <+157>: movl   $0x1, (%rax)
Target 0: (russian-doom) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
  * frame #0: 0x000000010078627e libSDL2-2.0.0.dylib`Cocoa_WarpMouseGlobal + 142
    frame #1: 0x0000000100082e9c russian-doom`I_ShutdownGraphics at i_video.c:392:13
    frame #2: 0x00000001000a3d04 russian-doom`I_Quit at i_system.c:200:9
    frame #3: 0x000000010002162a russian-doom`M_QuitResponse(confirmed=true) at m_menu.c:6891:5
    frame #4: 0x0000000100020bf2 russian-doom`M_Responder(ev=0x0000000100403b30) at m_menu.c:7282:13
    frame #5: 0x000000010000c761 russian-doom`D_ProcessEvents at d_main.c:358:13
    frame #6: 0x0000000100078b4e russian-doom`BuildNewTic at d_loop.c:166:5
    frame #7: 0x0000000100078ae0 russian-doom`NetUpdate at d_loop.c:267:14
    frame #8: 0x00000001000795bf russian-doom`TryRunTics at d_loop.c:803:2
    frame #9: 0x000000010000e078 russian-doom`D_DoomLoop at d_main.c:932:9
    frame #10: 0x0000000100012917 russian-doom`D_DoomMain at d_main.c:3265:5
    frame #11: 0x000000010000332c russian-doom`main(argc=1, argv=0x00007ffeefbff8e0) at i_main.c:225:5
    frame #12: 0x00007fff2063cf3d libdyld.dylib`start + 1
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Russian Doom on a Mac
2. Exit Russian Doom
3. Segfault will appear (if using the terminal) or a popup saying Russian Doom exited and a problem was found (Cocoa popup)

### Your configuration

[russian-doom-ini.txt](https://github.com/JNechaevsky/russian-doom/files/7778650/russian-doom-ini.txt)

### Provide a Log

[Log.txt](https://github.com/JNechaevsky/russian-doom/files/7778656/Log.txt)

### LINKED ISSUE #337: [BUG] Crash on shutdown under Linux if fullscreen is enabled
### International Doom version

81a970c1b198f194868643a2f7af765cb4b2b7f7

### What Operating System are you using?

Linux

### What Build variant of International Doom are you using?

x64 (amd64, x86_64, win64)

### If Other OS or Build variant, please describe

NixOS, SDL2 2.0.20, SDL2_mixer 2.0.4

### Relevant hardware info

Intel i5-4310U, Intel HD Graphics 4400

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The game crashes on shutdown:
```
Thread 1 "inter-hexen" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e08451 in X11_WarpMouseGlobal () from /nix/store/w8djsmpbrin5h91bnmcxycxshf48gdiw-SDL2-2.0.20/lib/libSDL2-2.0.so.0
(gdb) bt
#0  0x00007ffff7e08451 in X11_WarpMouseGlobal () from /nix/store/w8djsmpbrin5h91bnmcxycxshf48gdiw-SDL2-2.0.20/lib/libSDL2-2.0.so.0
#1  0x000000000046787b in I_ShutdownGraphics ()
#2  0x0000000000481072 in I_Quit ()
#3  0x000000000041476e in MN_Responder ()
#4  0x0000000000408084 in H2_ProcessEvents ()
#5  0x0000000000462426 in BuildNewTic ()
#6  0x0000000000462634 in NetUpdate ()
#7  0x0000000000462d55 in TryRunTics ()
#8  0x00000000004073f3 in H2_GameLoop ()
#9  0x000000000040870f in D_DoomMain ()
#10 0x0000000000405de4 in main ()
(gdb) x/i $rip
=> 0x7ffff7e08451 <X11_WarpMouseGlobal+17>:     mov    0x5a8(%rax),%rax
(gdb) p $rax
$1 = 0
```

Commenting out X11_WarpMouseGlobal fixes the issue.
Related: #299

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Build inter-hexen on Linux with SDL2 2.0.20
2. Run inter-hexen in fullscreen mode
3. Exit the game normally

### Your configuration

https://gist.github.com/kmeaw/d0768649bcfae987e411066434e665cd

### Provide a Log

https://gist.github.com/kmeaw/1d58524dd1101e0241464d9a858b515a

### PR DESCRIPTION
**Pull request by Dasperal**
Fixes #337
Properly fixes #299 (needs testing)

Also some CI fixes and updates

### CODE REVIEW

File: src/i_video.c [hunk 1]
```diff
@@ -384,16 +384,13 @@ void I_ShutdownGraphics(void)
...
-        SDL_QuitSubSystem(SDL_INIT_VIDEO);
-
         // [JN] Place mouse cursor to the center of the screen.
-        // Not safe for Mac retina displays, may cause a segfault.
-        #ifndef APPLE
-		if (fullscreen)
-		{
+        if (fullscreen)
+        {
             SDL_WarpMouseGlobal(w / 2, h / 2);
```
Comment (kmeaw) [inline src/i_video.c:390]: SDL_QuitSubSystem(SDL_INIT_VIDEO) has a side-effect: it restores the screen resolution that was set prior to the game being run. By simply moving it after SDL_WarpMouseGlobal, the warp will be performed in the post-run resolution, not pre-run. In other words, if your desktop screen resolution is 1920x1080 and the game runs in 640x480 fullscreen, it would warp to (320;240), which is not the center of the screen (960;540). Would it match the intended behavior?

Comment (Dasperal) [reply src/i_video.c:390]: We use SDL_WINDOW_FULLSCREEN_DESKTOP for fullscreen, so screen resolution is not changed
